services:
  - type: web
    name: trip-ai
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: GROQ_MODEL
        value: openai/gpt-oss-20b
      - key: GROQ_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: TAVILY_API_KEY
        sync: false
      - key: OPENWEATHER_API_KEY
        sync: false
      - key: AVIATION_STACK_API_KEY
        sync: false

